#!/bin/bash

default_sink=$(pactl get-default-sink)

volume=$(pactl list sinks | grep -A 15 "$default_sink" | grep 'Volume:' | head -1 | awk '{print $5}' | tr -d '%')

mute_status=$(pactl list sinks | grep -A 15 "$default_sink" | grep 'Mute:' | awk '{print $2}')

RED='#FF0000'
GREEN='#00FF00'
YELLOW='#FFFF00'
RESET='#000000'

json_output=""

if [[ "$mute_status" == "yes" ]]; then
  json_output=$(echo "{\"full_text\": \"Muted\", \"color\": \"$RED\"}")
else
  if (( volume > 100 )); then
    json_output=$(echo "{\"full_text\": \"${volume}%\", \"color\": \"$RED\"}")
  elif (( volume > 50 )); then
    json_output=$(echo "{\"full_text\": \"${volume}%\"")
    
  fi
fi

echo $json_output
