#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=10

ICON_CHARGING=""        # Charging icon
ICON_DISCHARGING=""     # Discharging icon
ICON_FULL=""           # Full battery icon
ICON_LOW=""            # Low battery icon (for when below the urgent value)

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${ICON_CHARGING} ${BATTERY_POWER}%"
  echo "${ICON_CHARGING} ${BATTERY_POWER}%"
  echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
    echo "${ICON_LOW} ${BATTERY_POWER}%"
    echo "${ICON_LOW} ${BATTERY_POWER}%"
    echo ""
  else
    echo "${ICON_DISCHARGING} ${BATTERY_POWER}%"
    echo "${ICON_DISCHARGING} ${BATTERY_POWER}%"
    echo ""
  fi
else
  echo "${ICON_FULL} ${BATTERY_POWER}%"
  echo "${ICON_FULL} ${BATTERY_POWER}%"
  echo ""
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
