#!/bin/bash

# Check Bluetooth status
STATUS=$(bluetooth | grep -wo 'on')

if [[ "${STATUS}" = "on" ]]; then
  
  
  bluetoothctl devices | while read -r line; do
    DEVICE_ID=$(echo "$line" | awk '{print $2}')
    if bluetoothctl info "$DEVICE_ID" | grep -q "Connected: yes"; then
      echo "$DEVICE_ID"
    fi
  done | wc -l

else
  echo "Bluetooth is off"
fi
