#!/usr/bin/bash

URGENT_VALUE=25

PACKAGE_COUNT=$(apt list --upgradable 2>/dev/null | grep -c "upgradable")

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}"
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    echo "Urgent: More than ${URGENT_VALUE} updates!"
    exit 33
  fi
else
  echo "0"
fi
